const express = require('express')
const { getAllEquipment, getEquipment, createEquipment, updateEquipment, deleteEquipment } = require('../components/admin/equipment/equipmentController')
const { getAllMenu, getMenu, createMenu, updateMenu, deleteMenu } = require('../components/admin/menu/menuController')
const { getAllOrder, getOrder, createOrder, updateOrder, deleteOrder } = require('../components/admin/order/orderController')
const { login, register } = require('../components/auth/authController')
const route = express.Router()

route.get('/admin/getOrders', getAllOrder)
route.get('/admin/get_order', getOrder)
route.post('/admin/create_order', createOrder)
route.put('/admin/update_order', updateOrder)
route.delete('/admin/delete_order', deleteOrder)
route.get('/admin/getMenus', getAllMenu)
route.get('/admin/getmenu', getMenu)
route.post('/admin/create_menu', createMenu)
route.put('/admin/update_menu', updateMenu)
route.delete('/admin/delete_menu', deleteMenu)
route.get('/admin/getEquipments', getAllEquipment)
route.get('/admin/get_equipment', getEquipment)
route.post('/admin/create_equipment', createEquipment)
route.put('/admin/update_equipment', updateEquipment)
route.delete('/admin/delete_equipment', deleteEquipment)
route.post('/admin/login', login)
route.post('/admin/register', register)
module.exports = route
