const express = require('express')
const { getAllOrder, getOrder, createOrder, updateOrder, deleteOrder, getAllMenu, getMenu, createMenu, updateMenu, deleteMenu, deleteEquipment, getAllEquipment, getEquipment, createEquipment, updateEquipment } = require('../components/admin/adminControllers')
const route = express.Router()

route.get('/admin/getOrders', getAllOrder)
route.get('/admin/get_order', getOrder)
route.post('/admin/create_order', createOrder)
route.put('/admin/update_order', updateOrder)
route.delete('/admin/delete_order', deleteOrder)
route.get('/admin/getMenus', getAllMenu)
route.get('/admin/getmenu', getMenu)
route.post('/admin/create_menu', createMenu)
route.put('/admin/update_menu', updateMenu)
route.delete('/admin/delete_menu', deleteEquipment)
route.get('/admin/getEquipments', getAllEquipment)
route.get('/admin/get_equipment', getEquipment)
route.post('/admin/create_equipment', createEquipment)
route.put('/admin/update_equipment', updateEquipment)
route.delete('/admin/delete_equipment', deleteEquipment)
module.exports = route
